# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1147, 719)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab2360 = QtGui.QTabWidget(self.centralwidget)
        self.tab2360.setGeometry(QtCore.QRect(150, 10, 991, 691))
        self.tab2360.setStyleSheet(_fromUtf8(""))
        self.tab2360.setObjectName(_fromUtf8("tab2360"))
        self.tab2400 = QtGui.QWidget()
        self.tab2400.setObjectName(_fromUtf8("tab2400"))
        self.mplwindow = QtGui.QWidget(self.tab2400)
        self.mplwindow.setGeometry(QtCore.QRect(240, -30, 721, 421))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName(_fromUtf8("mplwindow"))
        self.mplvl = QtGui.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.widget_2 = QtGui.QWidget(self.mplwindow)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.mplvl.addWidget(self.widget_2)
        self.pauseButton = QtGui.QPushButton(self.tab2400)
        self.pauseButton.setGeometry(QtCore.QRect(70, 380, 71, 41))
        self.pauseButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 128, 0);"))
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.tableWidget = QtGui.QTableWidget(self.tab2400)
        self.tableWidget.setGeometry(QtCore.QRect(10, 441, 781, 211))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.sweepButton = QtGui.QPushButton(self.tab2400)
        self.sweepButton.setGeometry(QtCore.QRect(0, 380, 71, 41))
        self.sweepButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.sweepButton.setObjectName(_fromUtf8("sweepButton"))
        self.stopButton = QtGui.QPushButton(self.tab2400)
        self.stopButton.setGeometry(QtCore.QRect(140, 380, 71, 41))
        self.stopButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Helvetica\";"))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.paraGroup = QtGui.QGroupBox(self.tab2400)
        self.paraGroup.setGeometry(QtCore.QRect(0, -10, 241, 271))
        self.paraGroup.setTitle(_fromUtf8(""))
        self.paraGroup.setObjectName(_fromUtf8("paraGroup"))
        self.formLayoutWidget = QtGui.QWidget(self.paraGroup)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 50, 231, 231))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.paraLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.paraLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.paraLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paraLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.paraLayout.setObjectName(_fromUtf8("paraLayout"))
        self.modeLabel = QtGui.QLabel(self.paraGroup)
        self.modeLabel.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.modeLabel.setStyleSheet(_fromUtf8("font: 18pt \"Helvetica\";\n"
"border-color: rgb(0, 0, 0);"))
        self.modeLabel.setObjectName(_fromUtf8("modeLabel"))
        self.modeComboBox = QtGui.QComboBox(self.paraGroup)
        self.modeComboBox.setGeometry(QtCore.QRect(70, 20, 151, 26))
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.saveButton = QtGui.QPushButton(self.tab2400)
        self.saveButton.setGeometry(QtCore.QRect(809, 451, 111, 51))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.tab2360.addTab(self.tab2400, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.mplwindow_2 = QtGui.QWidget(self.tab_2)
        self.mplwindow_2.setGeometry(QtCore.QRect(350, 30, 451, 401))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow_2.sizePolicy().hasHeightForWidth())
        self.mplwindow_2.setSizePolicy(sizePolicy)
        self.mplwindow_2.setObjectName(_fromUtf8("mplwindow_2"))
        self.mplvl_2 = QtGui.QVBoxLayout(self.mplwindow_2)
        self.mplvl_2.setObjectName(_fromUtf8("mplvl_2"))
        self.widget_3 = QtGui.QWidget(self.mplwindow_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.mplvl_2.addWidget(self.widget_3)
        self.pauseButton_2 = QtGui.QPushButton(self.tab_2)
        self.pauseButton_2.setGeometry(QtCore.QRect(510, 450, 111, 41))
        self.pauseButton_2.setObjectName(_fromUtf8("pauseButton_2"))
        self.tab2360.addTab(self.tab_2, _fromUtf8(""))
        self.configLabel = QtGui.QLabel(self.centralwidget)
        self.configLabel.setGeometry(QtCore.QRect(-435, 473, 451, 20))
        self.configLabel.setText(_fromUtf8(""))
        self.configLabel.setObjectName(_fromUtf8("configLabel"))
        self.startGroup = QtGui.QGroupBox(self.centralwidget)
        self.startGroup.setGeometry(QtCore.QRect(10, 20, 131, 411))
        self.startGroup.setTitle(_fromUtf8(""))
        self.startGroup.setObjectName(_fromUtf8("startGroup"))
        self.scanButton = QtGui.QPushButton(self.startGroup)
        self.scanButton.setGeometry(QtCore.QRect(5, 10, 81, 41))
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.verticalLayoutWidget = QtGui.QWidget(self.startGroup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 121, 211))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.instruLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.instruLayout.setObjectName(_fromUtf8("instruLayout"))
        self.configButton = QtGui.QPushButton(self.startGroup)
        self.configButton.setGeometry(QtCore.QRect(10, 300, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(14)
        font.setItalic(False)
        self.configButton.setFont(font)
        self.configButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);\n"
"alternate-background-color: rgb(179, 179, 179);\n"
""))
        self.configButton.setAutoDefault(False)
        self.configButton.setDefault(False)
        self.configButton.setFlat(False)
        self.configButton.setObjectName(_fromUtf8("configButton"))
        self.connectButton = QtGui.QPushButton(self.startGroup)
        self.connectButton.setGeometry(QtCore.QRect(10, 360, 61, 31))
        self.connectButton.setAutoFillBackground(False)
        self.connectButton.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 440, 131, 192))
        self.listWidget.setMovement(QtGui.QListView.Free)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab2360.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pauseButton.setText(_translate("MainWindow", "Pause", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time Stamp", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y", None))
        self.sweepButton.setText(_translate("MainWindow", "Sweep", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.modeLabel.setText(_translate("MainWindow", "Mode", None))
        self.modeComboBox.setItemText(0, _translate("MainWindow", "Voltage Bias", None))
        self.modeComboBox.setItemText(1, _translate("MainWindow", "Voltage Sweep", None))
        self.modeComboBox.setItemText(2, _translate("MainWindow", "Current Sweep", None))
        self.modeComboBox.setItemText(3, _translate("MainWindow", "Current Bias", None))
        self.modeComboBox.setItemText(4, _translate("MainWindow", "Voltage Customized", None))
        self.modeComboBox.setItemText(5, _translate("MainWindow", "Current Customized", None))
        self.saveButton.setText(_translate("MainWindow", "Save Data", None))
        self.tab2360.setTabText(self.tab2360.indexOf(self.tab2400), _translate("MainWindow", "2400", None))
        self.pauseButton_2.setText(_translate("MainWindow", "Pause", None))
        self.tab2360.setTabText(self.tab2360.indexOf(self.tab_2), _translate("MainWindow", "2360", None))
        self.scanButton.setText(_translate("MainWindow", "Scan", None))
        self.configButton.setText(_translate("MainWindow", "Assign", None))
        self.connectButton.setText(_translate("MainWindow", "Connect", None))

