import visa
rm=visa.ResourceManager()
my_instrument = rm.open_resource('GPIB::22::INSTR')
my_instrument.write("*RST")
my_instrument.write(":SENS:FUNC:CONC OFF")
my_instrument.write(":SOUR:FUNC CURR")
my_instrument.write(":SENS:FUNC 'VOLT:DC'")
my_instrument.write(":SENS:VOLT:PROT 1")
my_instrument.write(":SOUR:CURR:START 1E-3")
my_instrument.write(":SOUR:CURR:STOP 10E-3")
my_instrument.write(":SOUR:CURR:STEP 1E-3")
my_instrument.write(":SOUR:CURR:MODE SWE")
my_instrument.write(":SOUR:SWE:RANG AUTO")
my_instrument.write(":SOUR:SWE:SPAC LIN")
my_instrument.write(":TRIG:COUN 10")
my_instrument.write(":SOUR:DEL 0.1")
my_instrument.write(":OUTP ON")
my_instrument.write(":READ")
my_instrument.write(":OUTP OFF")
a = my_instrument.read()

import visa
rm=visa.ResourceManager()
my_instrument = rm.open_resource('GPIB::22::INSTR')
my_instrument.write("*RST")
my_instrument.write(":SOUR:FUNC VOLT")
my_instrument.write(":SENS:FUNC 'CURR:DC'")
my_instrument.write(":SENS:CURR:PROT 10E-3")
my_instrument.write(":SOUR:VOLT:START 1")
my_instrument.write(":SOUR:VOLT:STOP 10")
my_instrument.write(":SOUR:VOLT:STEP 1")
my_instrument.write(":SOUR:VOLT:MODE SWE")
#my_instrument.write(":SOUR:VOLT:MODE LIST")
#my_instrument.write(":SOUR:LIST:VOLT 7,1,3,8,2")   #custom sweep 7v, 1v, 3v ....
my_instrument.write(":SOUR:SWE:RANG AUTO")
my_instrument.write(":SOUR:SWE:SPAC LIN")  #LOG for log, LIN for linear
my_instrument.write(":TRIG:COUN 10")  #should be multiples of sweep points, if 20 , will sweep twice
my_instrument.write(":SOUR:DEL 0.1")
my_instrument.write(":SENS:CURR:RANG 10E-3")
#my_instrument.write(":SENS:CURR:RANG: AUTO ON")
my_instrument.write(":FORM:ELEM CURR") #only read current values
my_instrument.write(":OUTP ON")
my_instrument.write(":READ?")
my_instrument.write(":OUTP OFF")
a = my_instrument.read()